---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-east-1
  version: "1.19"
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d', 'us-east-1f']


managedNodeGroups:
- name: nodegroup-cpu
  instanceType: m5.large
  minSize: 4
  maxSize: 5
  desiredCapacity: 4
  
# - name: nodegroup-gpu
#   instanceType: p2.xlarge
#   volumeSize: 50
#   minSize: 1
#   maxSize: 2
#   desiredCapacity: 1
#   tags:
#     "k8s.io/cluster-autoscaler/node-template/label/nodepool": "p2_xlarge"
#   labels:
#     "nodepool": "p2_xlarge"
#   taints:
#     p2_xlarge: "p2_xlarge:NoSchedule"

# nodeGroups:
# - name: nodegroup
#   minSize: 4
#   maxSize: 5
#   desiredCapacity: 4
#   instanceType: m5.large
  # ssh:
  #   publicKeyName: k8s
  #   enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

# secretsEncryption:
#   keyARN: 
